Repository linux-pam/linux-pam, pull requests merged in 2023-01, with the labels that each got.

#511 pam_listfile: fix pointer misuse leading to data corruption
  modules/pam_listfile/pam_listfile.c
Labels: bug

#519 .github: remove x86 and x32 jobs
  .github/workflows/ci.yml
Labels: tests

#518 pam_selinux: treat getenforce failures as enforcing
  modules/pam_selinux/pam_selinux.c
Labels: enhancement

#525 examples: ignore generated tty_conv
  examples/.gitignore
Labels: build issue
