Repository linux-pam/linux-pam, pull requests merged in 2023-12, with the labels that each got.

#645 pam_faildelay: validate parameter ranges
  modules/pam_faildelay/pam_faildelay.c
Labels: bug

#646 pam_setquota: plug memory leak
  modules/pam_setquota/pam_setquota.c
Labels: bug

#651 libpam: treat NUL in passwd files correctly
  libpam/pam_modutil_check_user.c
  modules/pam_localuser/tst-pam_localuser-retval.c
Labels: enhancement

#652 pam_unix: handle invalid names in _unix_getpwnam
  modules/pam_unix/support.c
Labels: bug

#656 pam_unix: use correct number of rounds
  modules/pam_unix/support.c
Labels: bug

#657 pam_unix: check str to integer conversions
  modules/pam_unix/passverify.c
  modules/pam_unix/support.c
Labels: enhancement

#654 pam_unix: fix possible shadow signed overflows
  modules/pam_unix/passverify.c
Labels: bug

#664 pam_shells: fix regression (no release)
  modules/pam_shells/pam_shells.c
Labels: bug

#659 Assume getline exists
  configure.ac
  libpam/pam_modutil_searchkey.c
  modules/pam_pwhistory/opasswd.c
  modules/pam_shells/pam_shells.c
Labels: cleanup

#661 pam_unix: simplify save_old_password
  modules/pam_unix/passverify.c
Labels: cleanup

#662 pam_limits: avoid sscanf in parse_config_file
  modules/pam_limits/pam_limits.c
Labels: cleanup

#663 pam_xauth: simplify check_acl
  modules/pam_xauth/pam_xauth.c
Labels: cleanup

#665 pam_unix: sync expiry checks with shadow
  modules/pam_unix/passverify.c
Labels: enhancement

#667 treewide: assume free(NULL) is no-op
  doc/specs/parse_y.y
  libpam/include/security/_pam_macros.h
  libpam/pam_modutil_cleanup.c
  libpam/pam_modutil_getgrgid.c
  libpam/pam_modutil_getgrnam.c
  libpam/pam_modutil_getpwnam.c
  libpam/pam_modutil_getpwuid.c
  libpam/pam_modutil_getspnam.c
  libpamc/pamc_load.c
  libpamc/test/modules/pam_secret.c
  modules/pam_filter/pam_filter.c
  modules/pam_listfile/pam_listfile.c
  modules/pam_namespace/argv_parse.c
  modules/pam_stress/pam_stress.c
  modules/pam_timestamp/hmac_openssl_wrapper.c
  modules/pam_unix/pam_unix_auth.c
  modules/pam_xauth/pam_xauth.c
Labels: cleanup

#668 treewide: store strlen results in size_t
  libpam/pam_misc.c
  libpamc/pamc_load.c
  modules/pam_access/pam_access.c
  modules/pam_debug/pam_debug.c
  modules/pam_namespace/pam_namespace.c
  modules/pam_unix/support.c
Labels: bug

#670 pam_namespace: handle huge namespace.conf lines
  modules/pam_namespace/argv_parse.c
Labels: bug

#673 libpam: remove function prefixes in debug messages
  libpam/pam_auth.c
  libpam/pam_end.c
  libpam/pam_misc.c
  libpam/pam_password.c
  libpam/pam_start.c
Labels: cleanup

#676 pam_access: fix nul byte handling in config
  modules/pam_access/pam_access.c
Labels: bug

#672 libpam: reduce memory usage of _pam_mkargv
  libpam/pam_misc.c
Labels: enhancement

#678 pam_motd: fail if too many motd files encountered
  modules/pam_motd/pam_motd.c
Labels: bug

#679 pam_timestamp_check: fix potential null pointer dereference on error path
  modules/pam_timestamp/pam_timestamp.c
Labels: bug

#681 unix_chkpwd, unix_update: Use exit codes 128+ on signals
  modules/pam_unix/passverify.c
Labels: enhancement

#682 pam_listfile: add a test for return values
  modules/pam_listfile/Makefile.am
  modules/pam_listfile/tst-pam_listfile-retval.c
Labels: tests
