Repository linux-pam/linux-pam, pull requests merged in 2024-08, with the labels that each got.

#818 pam_faillock: silence compilation warning
  modules/pam_faillock/main.c
Labels: build issue

#815 configure.ac: fix typo in the help message for --enable-lastlog
  configure.ac
Labels: cleanup

#816 libpam_misc: Use ECHOCTL in the terminal input
  libpam_misc/misc_conv.c
Labels: enhancement
