Repository linux-pam/linux-pam, pull requests merged in 2024-09, with the labels that each got.

#826 pam_limits: use systemd-logind instead of utmp (#822)
  modules/pam_limits/Makefile.am
  modules/pam_limits/pam_limits.c
Labels: enhancement

#827 pam_userdb: don't overwrite free'd memory
  modules/pam_userdb/pam_userdb.c
Labels: bug

#830 examples/tty_conv: fix potential out of bound write in readline()
  examples/tty_conv.c
Labels: examples
