Repository linux-pam/linux-pam, pull requests merged in 2024-01, with the labels that each got.

#683 pam listfile.8: minor fixes and enhancements
  modules/pam_listfile/pam_listfile.8.xml
Labels: documentation

#675 pam_exec: allow also expose_authtok for password PAM_TYPE
  modules/pam_exec/pam_exec.8.xml
  modules/pam_exec/pam_exec.c
Labels: enhancement

#691 pam_namespace: validate amount of uids in config
  modules/pam_namespace/pam_namespace.c
Labels: bug

#692 configure.ac: remove unneeded function checks
  configure.ac
Labels: cleanup

#693 pam_unix: avoid reading uninitialized variable
  modules/pam_unix/pam_unix_passwd.c
Labels: bug

#694 pam_unix: use getline in _unix_getpwnam
  modules/pam_unix/support.c
Labels: enhancement, cleanup

#686 pam_unix/passverify: always run the helper to obtain shadow password file entries
  modules/pam_unix/passverify.c
Labels: enhancement

#704 libpam: use correct function definition
  libpam/pam_handlers.c
Labels: cleanup

#699 libpam: handle long delays properly
  libpam/pam_delay.c
Labels: enhancement

#700 libpam: use getrandom if possible
  configure.ac
  libpam/pam_delay.c
Labels: enhancement

#707 pam_limits: prevent overflow with very long line
  modules/pam_limits/pam_limits.c
Labels: bug

#708 pam_access: avoid group name truncation
  modules/pam_access/pam_access.c
Labels: bug

#709 pam_unix: do not truncate user names
  modules/pam_unix/passverify.c
  modules/pam_unix/unix_chkpwd.c
Labels: bug

#714 pam_env: allow escaping of escape character
  modules/pam_env/pam_env.c
  modules/pam_env/tst-pam_env-retval.c
Labels: enhancement

#715 pam_listfile: treat \r like \n
  modules/pam_listfile/pam_listfile.c
Labels: enhancement

#717 pam_access: add quiet_log option
  modules/pam_access/pam_access.8.xml
  modules/pam_access/pam_access.c
Labels: enhancement

#719 treewide: remove unused defines
  libpam/pam_modutil_searchkey.c
  modules/pam_env/pam_env.c
  modules/pam_faillock/faillock_config.h
  modules/pam_pwhistory/opasswd.c
Labels: cleanup

#723 pam_unix: fix regressions
  modules/pam_unix/pam_unix_passwd.c
  modules/pam_unix/passverify.c
Labels: bug

#724 pam_unix: do not allow comma as field separator
  modules/pam_unix/pam_unix_passwd.c
  modules/pam_unix/passverify.c
Labels: bug

#725 pam_pwhistory: parse opasswd lines verbatim
  modules/pam_pwhistory/opasswd.c
Labels: bug, cleanup

#729 ci: bump actions/checkout to v4
  .github/workflows/ci.yml
Labels: build issue

#737 libpam: fix build with --enable-read-both-confs
  libpam/pam_handlers.c
Labels: build issue

#739 pam_env: check VENDORDIR after config.h inclusion
  modules/pam_env/pam_env.c
Labels: bug

#740 pam_env: fix --enable-vendordir fallback logic
  modules/pam_env/pam_env.c
Labels: bug

#741 pam_env: remove escaped newlines from econf lines
  modules/pam_env/pam_env.c
Labels: bug

#742 libpam_misc: use size_t for sizes
  libpam_misc/help_env.c
Labels: bug

#744 pam_unix: do not warn if password aging disabled
  modules/pam_unix/passverify.c
Labels: bug

#746 build: correctly set WITH_SELINUX conditional
  configure.ac
Labels: bug, build issue

#748 pam_namespace: use sed instead of awk in namespace.init
  modules/pam_namespace/namespace.init
Labels: enhancement

#752 pam_faildelay: fix compilation warnings on 32bit platforms
  modules/pam_faildelay/pam_faildelay.c
Labels: build issue

#754 modules: add pamc headers to the search path only when needed
  modules/pam_access/Makefile.am
  modules/pam_canonicalize_user/Makefile.am
  modules/pam_debug/Makefile.am
  modules/pam_deny/Makefile.am
  modules/pam_echo/Makefile.am
  modules/pam_env/Makefile.am
  modules/pam_exec/Makefile.am
  modules/pam_faildelay/Makefile.am
  modules/pam_faillock/Makefile.am
  modules/pam_filter/Makefile.am
  modules/pam_filter/upperLOWER/Makefile.am
  modules/pam_ftp/Makefile.am
  modules/pam_group/Makefile.am
  modules/pam_issue/Makefile.am
  modules/pam_keyinit/Makefile.am
  modules/pam_lastlog/Makefile.am
  modules/pam_limits/Makefile.am
  modules/pam_listfile/Makefile.am
  modules/pam_localuser/Makefile.am
  modules/pam_loginuid/Makefile.am
  modules/pam_mail/Makefile.am
  modules/pam_mkhomedir/Makefile.am
  modules/pam_motd/Makefile.am
  modules/pam_namespace/Makefile.am
  modules/pam_nologin/Makefile.am
  modules/pam_permit/Makefile.am
  modules/pam_pwhistory/Makefile.am
  modules/pam_rhosts/Makefile.am
  modules/pam_rootok/Makefile.am
  modules/pam_securetty/Makefile.am
  modules/pam_selinux/Makefile.am
  modules/pam_sepermit/Makefile.am
  modules/pam_setquota/Makefile.am
  modules/pam_shells/Makefile.am
  modules/pam_stress/Makefile.am
  modules/pam_succeed_if/Makefile.am
  modules/pam_time/Makefile.am
  modules/pam_timestamp/Makefile.am
  modules/pam_tty_audit/Makefile.am
  modules/pam_umask/Makefile.am
  modules/pam_unix/Makefile.am
  modules/pam_userdb/Makefile.am
  modules/pam_usertype/Makefile.am
  modules/pam_warn/Makefile.am
  modules/pam_wheel/Makefile.am
  modules/pam_xauth/Makefile.am
Labels: build issue, cleanup

#753 pam_faildelay: improve delay parsing
  modules/pam_faildelay/pam_faildelay.c
Labels: enhancement

#755 libpam_internal: supply debug functionality
  Makefile.am
  configure.ac
  libpam/Makefile.am
  libpam/include/security/_pam_macros.h
  libpam_internal/Makefile.am
  libpam_internal/pam_debug.c
  libpam_misc/Makefile.am
  libpamc/Makefile.am
  modules/pam_access/Makefile.am
  modules/pam_debug/Makefile.am
  modules/pam_env/Makefile.am
  modules/pam_group/Makefile.am
  modules/pam_issue/Makefile.am
  modules/pam_lastlog/Makefile.am
  modules/pam_limits/Makefile.am
  modules/pam_mail/Makefile.am
  modules/pam_mkhomedir/Makefile.am
  modules/pam_motd/Makefile.am
  modules/pam_permit/Makefile.am
  modules/pam_stress/Makefile.am
  modules/pam_time/Makefile.am
  modules/pam_unix/Makefile.am
  tests/Makefile.am
Labels: cleanup

#757 pam_unix: try to set uid to 0 for unix_chkpwd
  modules/pam_unix/pam_unix_acct.c
  modules/pam_unix/support.c
Labels: enhancement
